version: '3'

services:
  mysqldb-availability:
    container_name: mysqldb-availability
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: availability-service
      MYSQL_ROOT_PASSWORD: mysql

  appointment-service:
    image: appointmentservice
    restart: always
    build: .
    ports:
      - '8082:8082'
    depends_on:
      - mysqldb-availability
    environment:
      MYSQL_HOST: mysqldb-availability
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_PORT: 3306

volumes:
  mysql-data: